### ISSUE TITLE
Data not refreshing

### ISSUE THREAD

**Issue by Sholofly** [xirixiz/home-assistant-config#1]
Hi, as mentioned in the Home-assistant forum, the garbage component is not refreshing data.
When i restart HASS the data is up-to-date again.

**Comment by Voxxie** [comment]
I do have the same issue.

**Comment by xirixiz** [comment]
Perhaps it has something to do with async. Could you give this version a try: https://github.com/xirixiz/home-assistant/blob/8e5ce6164ada798a067cebc86e861557f4816590/custom_components/sensor/mijnafvalwijzer.py

**Comment by xirixiz** [comment]
Or try version 1.0.2...

**Comment by Sholofly** [comment]
Problem seems to be solved.
