### ISSUE TITLE
change paths

### ISSUE THREAD

**Issue by IIIdefconIII** [xirixiz/home-assistant-config#6]
from 0.91 you need to change the paths from  "/custom_components/sensor/mijnafvalwijzer.py", to  "/custom_components/mijnafvalwijzer/sensor.py",

**Comment by xirixiz** [comment]
Thanks for the heads-up!

**Comment by xirixiz** [comment]
Once 0.9x officially has been released I will change paths. Cheers!

**Comment by xirixiz** [comment]
Done!
