### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by IIIdefconIII** [xirixiz/home-assistant-config#7]
HA v 0.88
linux virt env

Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/helpers/entity.py", line 221, in async_update_ha_state
    await self.async_device_update()
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/helpers/entity.py", line 349, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/homeassistant/.homeassistant/custom_components/mijnafvalwijzer/sensor.py", line 137, in update
    for item in self.data.data:
TypeError: 'NoneType' object is not iterable

**Comment by xirixiz** [comment]
Do you use version 2.0.7, I just released it Tonight. Mijnafvalwijzer added some odd spaces to the output, so I had to create a bugfix release.

**Comment by IIIdefconIII** [comment]
Yes i just updated it a few minutes ago

**Comment by IIIdefconIII** [comment]
could it be cause i changed the path to /custom_components/mijnafvaltwijzer/sensor.py? cause this is necessarily from 0.91

**Comment by xirixiz** [comment]
Could be. Did you check the file /custom_components/mijnafvalwijzer/sensor.py? Does it say version 2.0.7?

**Comment by IIIdefconIII** [comment]
Yes, ;) i do use 2.0.7 like i said i just updated it 1 hours ago

**Comment by xirixiz** [comment]
That's what I wanted to see, I thought maybe custom_updater placed it at the "old" path 😄

**Comment by xirixiz** [comment]
I`ll verify it Tomorrow

**Comment by IIIdefconIII** [comment]
cool thanks and welterusten ;)

**Comment by IIIdefconIII** [comment]
hi man, yesterday you stated you will probably drop this component cause of the email you got from afvalwijzer, i was thinking, is it possible to convert this component to static dates? I know every Monday the trash is picked up. So instead of looking to the calendar, just use hard data. Thats something we could accomplish with automatons is think.

**Comment by xirixiz** [comment]
3.0.0 released!
